if(WIN32)
	set(FileName 7z.exe)
	set(FilePathDownloaded ${c_ProjectTempDirPath}/${FileName})
	set(ExeFilePath7z ${FilePathDownloaded})
	if(NOT EXISTS "${FilePathDownloaded}")
		set(SrcFilePath ${c_StorageAddrPath}/Tool/${c_HostPlatform}/7z/${FileName})
		set(SrcCloudFilePath https://drive.usercontent.google.com/download?id=1Fy3nRQ9X0F66661sEm4sSyVoonRA7jpL&export=download&authuser=0&confirm=t&uuid=ccc48ec8-fca3-4976-a11b-c383a3a1f684&at=ALoNOglmSykByzx1IWYzybSKBZ6k:1748682593962)
		if((NOT c_IsLocalStorageReachable) AND SrcCloudFilePath)
			set(SrcFilePath ${SrcCloudFilePath})
		endif()
		set(DstFilePath ${FilePathDownloaded})
		message(STATUS "Downloading ${DstFilePath} from ${SrcFilePath}")
		file(DOWNLOAD "${SrcFilePath}" "${DstFilePath}"
			 STATUS status
			 #SHOW_PROGRESS
		)
		if(status EQUAL 0)
			message(STATUS "File downloaded successfully.")
		else()
			message(FATAL_ERROR "${c_StorageConfigDownloadingFailedTips}")
		endif()
		set(FileName 7z.dll)
		set(FilePathDownloaded ${c_ProjectTempDirPath}/${FileName})
		set(SrcFilePath ${c_StorageAddrPath}/Tool/${c_HostPlatform}/7z/${FileName})
		set(SrcCloudFilePath https://drive.usercontent.google.com/download?id=1rOzxAdxCib7bOr34l-2zLN6QwYd5pBXE&export=download&authuser=0&confirm=t&uuid=1ee09cb5-2e31-4e4f-901d-9ee9bb26f7b3&at=ALoNOgl7G7zgU09Ktv1-AHPt3yTC:1748682609712)
		if((NOT c_IsLocalStorageReachable) AND SrcCloudFilePath)
			set(SrcFilePath ${SrcCloudFilePath})
		endif()
		set(DstFilePath ${FilePathDownloaded})
		message(STATUS "Downloading ${DstFilePath} from ${SrcFilePath}")
		file(DOWNLOAD "${SrcFilePath}" "${DstFilePath}"
			 STATUS status
			 #SHOW_PROGRESS
		)
		if(status EQUAL 0)
			message(STATUS "File downloaded successfully.")
		else()
			message(FATAL_ERROR "${c_StorageConfigDownloadingFailedTips}")
		endif()
	endif()
endif()