set(c_RootGeneratedDirPath ${CMAKE_CURRENT_BINARY_DIR}/Generated)
set(c_RootSourceDirPath ${c_RootDirPath}/Source)
set(c_RootProjectDirPath ${c_RootDirPath}/Project)
set(c_RootTestDirPath ${c_RootDirPath}/Test)
set(c_RootThirdPartyDirPath ${c_RootDirPath}/ThirdParty)
get_filename_component(c_RootCMakeProjectFrameworkThirdPartyDirPath "${c_RootCMakeProjectFrameworkDirPath}/../ThirdParty" ABSOLUTE)