if(NOT c_ProjectBinDirPathDebug)
	message(FATAL_ERROR "This must be included after ProjectEnd.cmake")
endif()
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${c_ProjectBinDirPathDebug})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${c_ProjectBinDirPathRelease})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${c_ProjectLibDirPathDebug})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${c_ProjectLibDirPathRelease})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${c_ProjectLibDirPathDebug})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${c_ProjectLibDirPathRelease})