if(v_ZipFileName)
	set(DstDownloadedFilePath ${v_IntegratedToolRootDirPath}/${v_ZipFileName})
	if(c_ProjectPipelineSetup OR NOT EXISTS "${v_UnzippedDirPath}")
		set(SrcAddrZipFilePath ${v_SrcZipAddrFilePath})
		if((NOT c_IsLocalStorageReachable) AND v_SrcZipCloudFilePath)
			set(SrcAddrZipFilePath ${v_SrcZipCloudFilePath})
		endif()
		download_zip_replace_dir_if_not_exists(${SrcAddrZipFilePath} ${DstDownloadedFilePath} ${v_UnzippedDirPath} IsDownloaded)
	endif()
endif()
