set(DstDownloadedFilePath ${v_ImportedLibRootDirPath}/${v_ZipFileName})
if(c_ProjectPipelineSetup OR NOT EXISTS "${v_LibPlatformArchDirPath}")
	set(SrcAddrZipFilePath ${v_SrcZipAddrFilePath})
	if((NOT c_IsLocalStorageReachable) AND v_SrcZipCloudFilePath)
		set(SrcAddrZipFilePath ${v_SrcZipCloudFilePath})
	endif()
	#if (NOT v_LibPlatformArchDirPath)
	#	message(FATAL_ERROR "v_LibPlatformArchDirPath is empty")
	#endif()
	if (c_ProjectPipelineSetup)
		message("Delete unzipping directory ${v_UnzippedDirPath}")
		file(REMOVE_RECURSE "${v_UnzippedDirPath}")
	endif()
	download_zip_replace_dir_if_not_exists(${SrcAddrZipFilePath} ${DstDownloadedFilePath} ${v_UnzippedDirPath} ${v_LibPlatformArchDirPath} IsDownloaded)
endif()