#option(PROJECT_SETUP "Setup the project dependencies" OFF)
#option(PROJECT_RELEASE "Release the installed project" OFF)
define_enum(PROJECT_PIPELINE "Default" "PROJECT_PIPELINE has 3 options: 1. Default, Including Generate, Update, Build, Install 4 pipelines; 2. Setup; 3. Release" Default Setup Release)
set(c_ProjectPipelineDefault OFF)
set(c_ProjectPipelineSetup OFF)
set(c_ProjectPipelineRelease OFF)
if(PROJECT_PIPELINE STREQUAL "Default")
    set(c_ProjectPipelineDefault ON)
elseif(PROJECT_PIPELINE STREQUAL "Setup")
    set(c_ProjectPipelineSetup ON)
elseif(PROJECT_PIPELINE STREQUAL "Release")
    set(c_ProjectPipelineRelease ON)
else()
    message(FATAL_ERROR "Invalid PROJECT_PIPELINE value: ${PROJECT_PIPELINE}")
endif()