#option(PROJECT_SETUP "Setup the project dependencies" OFF)
#option(PROJECT_RELEASE "Release the installed project" OFF)
define_enum(PROJECT_PIPELINE "Default" "Project mode: DEBUG, RELEASE, TEST" Default Setup Release)
set(c_ProjectPipelineDefault OFF)
set(c_ProjectPipelineSetup OFF)
set(c_ProjectPipelineRelease OFF)
if(PROJECT_PIPELINE STREQUAL "Default")
    message(STATUS "Running Default flow: Generate project files and build.")
    set(c_ProjectPipelineDefault ON)
elseif(PROJECT_PIPELINE STREQUAL "Setup")
    message(STATUS "Running Setup flow: Deploy dependencies to output directory.")
    set(c_ProjectPipelineSetup ON)
elseif(PROJECT_PIPELINE STREQUAL "Release")
    message(STATUS "Running Release flow: Package and release.")
    set(c_ProjectPipelineRelease ON)
else()
    message(FATAL_ERROR "Invalid PROJECT_FLOW value: ${PROJECT_FLOW}")
endif()